# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 06:39
# Generated by Django 1.9.2 on 2016-07-14 04:34
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abductors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Abs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Adductors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Biceps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Calves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Forearms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Glutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hamstrings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lower_Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Middle_Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Neck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quadriceps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shoulders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Triceps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
            ],
        ),
    ]
