# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20160727_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
