# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_levels_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='name',
        ),
    ]
