# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_remove_weighttrends_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighttrends',
            name='profile_user',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to='goals.UserProfile'),
            preserve_default=False,
        ),
    ]
