# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_weighttrends_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighttrends',
            name='profile_user',
        ),
    ]
