# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_remove_weighttrends_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(null=True)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='WeightTrends',
        ),
    ]
