# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20160727_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightTrend',
        ),
    ]
