# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 19:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_for_calc', models.IntegerField()),
                ('weight_for_calc', models.IntegerField()),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('lunges', models.IntegerField()),
                ('sit_ups', models.IntegerField()),
                ('push_ups', models.IntegerField()),
                ('squats', models.IntegerField()),
                ('calf_raises', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=100)),
                ('directions', models.CharField(max_length=10000)),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=0)),
                ('day', models.CharField(choices=[('DayOne', 'DayOne'), ('DayTwo', 'DayTwo'), ('DayThree', 'DayThree')], default='DayOne', max_length=8)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForGraphing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField()),
                ('ibw', models.FloatField()),
                ('ibw_hamwi', models.FloatField()),
                ('current_weight', models.IntegerField(default=190)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelGrowthGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abslevel', models.FloatField()),
                ('leg', models.FloatField()),
                ('upperarm', models.FloatField()),
                ('lowerarm', models.FloatField()),
                ('back', models.FloatField()),
                ('chest', models.FloatField()),
                ('glutes', models.FloatField()),
                ('neck', models.FloatField()),
                ('overall', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 8, 25, 15, 34, 3, 42477))),
                ('month', models.IntegerField(default=8)),
                ('year', models.IntegerField(default=2016)),
                ('day', models.IntegerField(default=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelsgraph', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weightgraph',
            fields=[
                ('weight', models.IntegerField()),
                ('day', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 8, 25, 15, 34, 3, 26852))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightgraph', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
