# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 02:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 22, 10, 39, 793637)),
        ),
        migrations.AlterField(
            model_name='weightgraph',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightgraph', to=settings.AUTH_USER_MODEL),
        ),
    ]
