# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20160813_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 18, 3, 17, 46883)),
        ),
    ]
