# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20160813_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 18, 42, 39, 856618)),
        ),
    ]
