# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20160813_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgraphing',
            name='current_weight',
            field=models.IntegerField(default=190),
        ),
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 19, 0, 31, 808435)),
        ),
    ]
