# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20160814_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelsgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 0, 47, 38, 978920)),
        ),
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 0, 47, 38, 977413)),
        ),
    ]
