# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20160814_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_key', models.CharField(max_length=5)),
                ('ex_name', models.CharField(max_length=250)),
                ('ex_type', models.CharField(max_length=30)),
                ('ex_dif', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=100)),
                ('directions', models.CharField(max_length=10000)),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='levelsgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 8, 6, 59, 647988)),
        ),
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 8, 6, 59, 645986)),
        ),
    ]
