# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0012_auto_20160815_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('day', models.CharField(choices=[('DayOne', 'DayOne'), ('DayTwo', 'DayTwo'), ('DayThree', 'DayThree')], default='DayOne', max_length=8)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='levelsgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 13, 9, 1, 355785)),
        ),
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 13, 9, 1, 351785)),
        ),
    ]
