# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20160818_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 21, 35, 37, 652240)),
        ),
        migrations.AlterField(
            model_name='weightgraph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 21, 35, 37, 652240)),
        ),
    ]
